export class Const {
  // Use to validate keyboard events. e.g. KeyDown event.key
  public static readonly KEYBOARD_INVISIBLE_CHAR_KEYS = [
    'Backspace',
    'Tab',
    'Enter',
    'Shift',
    'Control',
    'Alt',
    'Pause',
    'CapsLock',
    'Escape',
    'PageUp',
    'PageDown',
    'End',
    'Home',
    'ArrowLeft',
    'ArrowUp',
    'ArrowRight',
    'ArrowDown',
    'PrintScreen',
    'Insert',
    'Delete',
    'Meta',
    'ContextMenu',
    'F1',
    'F2',
    'F3',
    'F4',
    'F5',
    'F6',
    'F7',
    'F8',
    'F9',
    'F10',
    'F11',
    'F12',
    'NumLock',
    'ScrollLock',
  ];

  // Use to validate keyboard events. e.g. KeyDown event.code
  public static readonly KEYBOARD_SPECIAL_CHAR_CODES = [
    'Semicolon',
    'Equal',
    'Comma',
    'Minus',
    'Period',
    'Slash',
    'Backquote',
    'BracketLeft',
    'Backslash',
    'BracketRight',
    'Quote',
  ];
}
